### ISSUE TITLE
Indexing Error in tree.write_summaries

### ISSUE THREAD

**Issue by rakstats** [ccdmb/BioDendro#10]
Below is the copy of the error we got while running tree.write_summaries.

We suspect it something to with iloc or loc in Pandas dataframe.

tree.write_summaries(path="results")

---------------------------------------------------------------------------
IndexingError                             Traceback (most recent call last)
<ipython-input-13-d312ca933079> in <module>()
      2 os.makedirs("results", exist_ok=True)
      3 
----> 4 tree.write_summaries(path="results")

~\SUMAN_RAKSHIT\CCDM_PROJECTS\BioDendro\BioDendro\cluster.py in write_summaries(self, path)
    316 
    317             # axis=1 cluster number not in csv and png output
--> 318             subtab = subtab.loc[:, subtab.any(axis=1)]
    319 
    320             csv_filename = pjoin(path,

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in __getitem__(self, key)
   1470             except (KeyError, IndexError):
   1471                 pass
-> 1472             return self._getitem_tuple(key)
   1473         else:
   1474             # we by definition only have the 0th axis

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in _getitem_tuple(self, tup)
    888                 continue
    889 
--> 890             retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
    891 
    892         return retval

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in _getitem_axis(self, key, axis)
   1866             return self._get_slice_axis(key, axis=axis)
   1867         elif com.is_bool_indexer(key):
-> 1868             return self._getbool_axis(key, axis=axis)
   1869         elif is_list_like_indexer(key):
   1870 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in _getbool_axis(self, key, axis)
   1491             axis = self.axis or 0
   1492         labels = self.obj._get_axis(axis)
-> 1493         key = check_bool_indexer(labels, key)
   1494         inds, = key.nonzero()
   1495         try:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py in check_bool_indexer(ax, key)
   2354         mask = isna(result._values)
   2355         if mask.any():
-> 2356             raise IndexingError('Unalignable boolean Series provided as '
   2357                                 'indexer (index of the boolean Series and of '
   2358                                 'the indexed object do not match')

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match

**Comment by darcyabjones** [comment]
Somehow we got the "axis" argument wrong in `subtab.any(axis = 1)`.
It should be `axis=0` to return an array of bools indicating which columns are not all false.

Fixed issue in the branch `fix_indexerror` and submitted PR.
